version: '3.5'
services:
  vonage-run:
    container_name: vonage-run
    build:
      context: .
      dockerfile: docker/run/Dockerfile
      args:
        PROJECTNAME_ARG: ${PROJECT_NAME}
    image: vonage:${PROJECT_NAME}
    volumes:
      - "./:/var/vonage-run"
    ports:
      - "8080:8080"
    labels:
      name: vonage-runner